name = "severkalendar"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

[vars]
# Environment variables should be set in the Cloudflare Dashboard for security,
# but we can list them here as placeholders if needed.
